### ISSUE TITLE
Un-verified email address able to be set as primary

### ISSUE THREAD

**Issue by hkarpf** [scott2b/django-multimail#12]
set_as_primary checks if the email is not verified and adds an error message, however it still allows the un-verified email to be set as the primary one.

**Comment by hkarpf** [comment]
@scott2b I think changing line 73 in multimail/views.py to
```
Take out -> else:
Put in -> elif email.is_verified():

```

**Comment by hkarpf** [comment]
Let me know if this fix gets implemented, I'd rather not due my own fork of your great code!

**Comment by scott2b** [comment]
fixed by #13
